Data Manipulation Exercise
========================================================

# Just making sure we still have the data

```{r}
siurl<-"http://water.epa.gov/type/lakes/assessmonitor/lakessurvey/upload/NLA2007_SampledLakeInformation_20091113.csv"
wqurl<-"http://water.epa.gov/type/lakes/assessmonitor/lakessurvey/upload/NLA2007_WaterQuality_20091123.csv"
luurl<-"http://water.epa.gov/type/lakes/assessmonitor/lakessurvey/upload/NLA2007_Buffer_Landuse_Metrics_20091022.csv"

si<-read.csv(siurl)
wq<-read.csv(wqurl)
lu<-read.csv(luurl)
```


# Subset data into just what we want

```{r}
si_subset<-si[c("SITE_ID","VISIT_NO","SITE_TYPE",
                         "STATE_NAME")]
wq_subset<-wq[c("SITE_ID","NTL","PTL","CHLA")]
lu_subset<-lu[c("SITE_ID","PCT_DEVELOPED_BUFR",
                "PCT_FOREST_BUFR","PCT_AGRIC_BUFR",
                "PCT_WETLAND_BUFR")]
```

# Create a single data frame

```{r}
nlam1<-merge(si_subset,wq_subset,by="SITE_ID")
nla<-merge(nlam1,lu_subset,by="SITE_ID")
```

# How many rows and columns in new data frame?

```{r}
nrow(nla)
ncol(nla)
```

# Calculate mean, median, max ... for each of the columns

```{r}
apply(nla[,5:11],2,summary)
```

# Write data to .csv

```{r}
write.csv(nla,"nla.csv",row.names=FALSE)
```
